services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: retail_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname Marwan --lastname Ahmed --role Admin --email admin@example.com || true &&
               airflow standalone"